class Contact {
  const Contact(
    this.name,
    this.role,
    this.address,
    this.phone,
    this.email,
    this.website,
  );

  final String name;
  final String role;
  final String address;
  final String phone;
  final String email;
  final String website;

  static const contacts = [
    Contact(
      'Antonio Peñaloza',
      'Biostatistician IV',
      '1 Cherokee Parkway',
      '804-575-0381',
      'antonio@google.com',
      'chiapas.mx',
    ),
    Contact(
      'Sara Gomez',
      'Mechanical Systems Engineer',
      '654 Monument Hill',
      '786-374-1734',
      'sara@google.com',
      'gomez.gov',
    ),
    Contact(
      'Regina rivero',
      'Information Systems Manager',
      '64962 Bashford Court',
      '314-318-3639',
      'regina@google.com',
      'rivero.com',
    ),
    Contact(
      'Andrea Simon',
      'Staff Accountant IV',
      '23 Meadow Vale Point',
      '337-125-3557',
      'andrea@google.com',
      'simon.org',
    ),
    Contact(
      'Mariana Ochoa',
      'Account Executive',
      '96 Fallview Terrace',
      '613-601-9077',
      'mariana@google.com',
      'ochoa.com',
    ),
    Contact(
      'Vanessa Monsreal',
      'Recruiting Manager',
      '7105 Red Cloud Drive',
      '336-308-8202',
      'vanessa@google.com',
      'monsreal.com',
    ),
    Contact(
      'Junior Ramayo',
      'Flutter developer',
      '9 Rusk Crossing',
      '999-602-3301',
      'junior@google.com',
      'ramayo.com',
    ),
    Contact(
      'Rodrigo Lopez',
      'Associate Professor',
      '49957 Michigan Drive',
      '371-946-7606',
      'rodrigo@google.com',
      'lopez.com',
    ),
    Contact(
      'Andres Hernandez',
      'Account Representative II',
      '6952 Almo Court',
      '909-544-6130',
      'andres@google.com',
      'hernandez.com',
    ),
    Contact(
      'Jordanna Xacur',
      'Design Engineer',
      '7569 Pond Lane',
      '155-907-8226',
      'jordana@google.com',
      'xacur.com',
    ),
    Contact(
      'Maria Gonzales',
      'Budget/Accounting Analyst IV',
      '745 Gateway Court',
      '937-551-4302',
      'maria@google.com',
      'gonzales.com',
    ),
    Contact(
      'Ana Reyes',
      'Media Manager II',
      '8403 Talmadge Drive',
      '175-331-5930',
      'ana@google.com',
      'reyes.com',
    ),
    Contact(
      'lucia Leon',
      'Analyst Programmer',
      '6 Morning Pass',
      '790-575-5543',
      'lucia@google.com',
      'leon.com',
    ),
    Contact(
      'Juan perez',
      'Software Engineer IV',
      '47858 Monument Terrace',
      '619-672-8470',
      'juan@google.com',
      'perez.com',
    ),
    Contact(
      'Barbara Boyance',
      'Account Coordinator',
      '32 Kropf Place',
      '839-854-2730',
      'barbara@google.com',
      'boyance.com',
    ),
    Contact(
      'Yolande Cyster',
      'Web Developer I',
      '337 Saint Paul Center',
      '636-156-8613',
      'ycysterf@dot.gov',
      'shinystat.com',
    ),
    Contact(
      'Jennee Bencher',
      'Programmer Analyst II',
      '27 Sauthoff Crossing',
      '715-609-7880',
      'jbencherg@japanpost.jp',
      'google.com.br',
    ),
    Contact(
      'Dyane Kairns',
      'Dental Hygienist',
      '02 3rd Lane',
      '455-267-0183',
      'dkairnsh@jalbum.net',
      'posterous.com',
    ),
    Contact(
      'Jonas Warlowe',
      'Recruiting Manager',
      '7888 Hallows Road',
      '968-821-6047',
      'jwarlowei@macromedia.com',
      'examiner.com',
    ),
    Contact(
      'Sofia Boyance',
      'Electrical Engineer',
      '936 Jana Crossing',
      '322-722-6715',
      'sofia@google.com',
      'boyance.com',
    ),
  ];
}